name: Cross-Platform Builds

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    name: Build (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        config:
          - name: linux-x64-clang
            os: ubuntu-latest
            preset: unixlike-clang-release
            output: linux-x64-clang
          - name: linux-x64-gcc
            os: ubuntu-latest
            preset: unixlike-gcc-release
            output: linux-x64-gcc

          - name: macOS-x64-clang
            os: macos-latest
            preset: unixlike-clang-release
            output: macOS-x64-clang
          - name: macOS-x64-gcc
            os: macos-latest
            preset: unixlike-gcc-release
            output: macOS-x64-gcc

          - name: windows-x64-clang
            os: windows-latest
            preset: windows-clang-release
            output: windows-x64-clang
          - name: windows-x64-msvc
            os: windows-latest
            preset: windows-msvc-release
            output: windows-x64-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run ${{ matrix.config.name }} Build
        uses: ./.github/actions/build/unix
        if: contains(matrix.config.os, 'ubuntu')
        with:
          config-name: ${{ matrix.config.name }}
          config-os: ${{ matrix.config.os }}
          config-preset: ${{ matrix.config.preset }}
          config-output: ${{ matrix.config.output }}

      - name: Run ${{ matrix.config.name }} Build
        uses: ./.github/actions/build/macos
        if: contains(matrix.config.os, 'macos')
        with:
          config-name: ${{ matrix.config.name }}
          config-os: ${{ matrix.config.os }}
          config-preset: ${{ matrix.config.preset }}
          config-output: ${{ matrix.config.output }}

      - name: Run ${{ matrix.config.name }} Build
        uses: ./.github/actions/build/windows
        if: contains(matrix.config.os, 'windows')
        with:
          config-name: ${{ matrix.config.name }}
          config-os: ${{ matrix.config.os }}
          config-preset: ${{ matrix.config.preset }}
          config-output: ${{ matrix.config.output }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: false
    
    steps:
      # Print current directory for debugging
      - name: Print current directory recursively
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -R
          echo "Contents of artifacts directory:"
          ls -R artifacts
          echo "Contents of build directory:"
          ls -R build
          echo "Contents of output directory:"
          ls -R output

      - name: Publish Artifacts
        uses: ./.github/actions/publish
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
